### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by jwijenbergh** [ramnes/git-playground#9]
### Issue description

everything is awesome

step 1: launched qtile
step 2: it worked???
step 3: ???
step 4: profit

### Version

999

### Backend

X11 (default), Wayland (experimental)

### Config

```python
no u
```

### Logs

```text
Exception occured: no log
```

### Required

- [X] I have searched past issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ramnes** [comment]
> ### Issue description
> everything is awesome
> 
> step 1: launched qtile step 2: it worked??? step 3: ??? step 4: profit

lold
